# Change these first
owner: jpleasants # Your GitHub organization or username, where this repository lives
repo: plesk11 # The name of this repository
delay: 2000 # 2 seconds

sites:
  - name: Plesk 11
    url: https://plesk11.samitsolutions.com
    port: 8443
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Tandoori Bitesdurham
    url: https://tandooribitesdurham.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Clintrial Research
    url: https://clintrialresearch.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: obsn
    url: https://obsn.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: cholanad
    url: https://cholanad.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Cmc  Buildinginc
    url: https://cmcbuildinginc.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: chaska Indiancuisine
    url: https://chaskaindiancuisine.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: carolina Retinaeye Care
    url: https://carolinaretinaeyecare.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Samit Solutions
    url: https://samitsolutions.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Our Health Partner
    url: https://ourhealthpartner.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Cloven Cardamom
    url: https://clovencardamom.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: vascular wellness
    url: https://vascularwellness.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Tandoori Bites
    url: https://tandooribites.net
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: triangl Ehearing
    url: https://trianglehearing.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Tandoor Chapelhill
    url: https://tandoorchapelhill.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
 
   

      

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /plesk8
  logoUrl: https://samitpublic.blob.core.windows.net/download/sam-it-dots(1).png
  name: SAM IT Solutions
  theme: night
  introTitle: "**Status** page highlighting active incidents, current status of endpoints, and historical data."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
